from fastapi import FastAPI
from pydantic import BaseModel
import google.generativeai as genai
import os
from mangum import Mangum
from fpdf import FPDF
from fastapi.responses import Response

app = FastAPI()

# 1. Setup Gemini
if "GEMINI_API_KEY" in os.environ:
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])

@app.get("/api/health")
async def health_check():
    return {"status": "ok", "message": "EngiBot API is running"}

@app.get("/api")
async def root():
    return {"status": "ok", "message": "EngiBot API Root. Use /api/chat for interactions."}

# 2. YOUR REAL STOCK (Prices & IDs)
PRODUCT_CATALOG = """
--- SELEC CONTROLLERS ---
[ID: TC544C] Selec Dual Display Temp Controller, 48x48mm, Relay/SSR Output. Price: 10,750 LKR
[ID: TC544A] Selec Economic Temp Controller, 48x48mm, Relay Output. Price: 11,850 LKR
[ID: HTC405] Selec Humidity & Temp Controller, 36x72mm. Price: 13,660 LKR
[ID: HTC307] Selec Humidity & Temp Controller, 96x96mm, RS485. Price: 33,070 LKR
[ID: TC303AX] Selec Single Display Controller, 96x96mm. Price: 10,310 LKR
[ID: PID500-U] Selec Universal PID, 48x48mm (Various Outputs). Price: ~19,800 - 32,000 LKR (Check specifics)
[ID: PID110] Selec PID Controller, 96x48mm. Price: 17,280 - 34,500 LKR
[ID: DTC524] Selec Dual Display PID, 48x48mm. Price: 7,025 LKR
[ID: TC513AX] Selec Single Display Controller, 48x48mm. Price: 10,600 LKR
[ID: TC244AX] Selec Dual Display Controller, 72x72mm. Price: 11,500 LKR

--- HANYOUNG NUX CONTROLLERS ---
[ID: AX4-1A] Hanyoung Digital Temp Controller, 48x48mm, Relay+SSR. Price: 16,230 LKR
[ID: AX4-3A] Hanyoung Controller, 48x48mm, 4-20mA Output. Price: 17,800 LKR
[ID: AX9-4A] Hanyoung Controller, 96x96mm, 4-20mA Output. Price: 21,900 LKR
[ID: VX4-USMA] Hanyoung Advanced Controller, Voltage Pulse, 48x48mm. Price: 19,290 LKR
[ID: VX4-RS485] Hanyoung Controller with RS485. Price: 26,430 LKR
"""

# 3. DEEP TECHNICAL DATA (Sourced from Datasheets)
TECHNICAL_DATA = """
--- SELEC TECHNICAL SPECS ---
1. TC544C / TC544A (48x48mm):
   - Display: 4-digit dual LED (White/Green).
   - Inputs: Thermocouple (J,K,T,R,S) or RTD (PT100).
   - Control Output: Relay (5A) or SSR (12V DC).
   - Accuracy: 0.25% FS (±1°C). Resolution: 0.1/1°C.
   - Supply: 90-270V AC/DC.
   - TC544A is the "Economic" version (Basic features).

2. HTC405 (36x72mm - Humidity):
   - Input: RH Sensor (5V HS-A-100) + RTD PT100.
   - Accuracy: RH ±1%, Temp 0.1%.
   - Output: Relay (Humidity ON-OFF, Temp ON-OFF/PID).
   - IP Rating: IP65 Front Face.

3. HTC307 (96x96mm - Humidity):
   - Advanced model with RS485 Modbus communication.
   - Auto-tuning PID for temperature.

4. PID500 / PID110 / PID330 Series:
   - Inputs: Universal (TC, RTD, Analog Signal).
   - Outputs: Selectable (Relay, SSR, 4-20mA, 0-10V).
   - Features: Heat-Cool PID, Dwell Timer, Ramp/Soak (128 steps).
   - Optional: RS485 Modbus (check specific part number).

--- HANYOUNG NUX TECHNICAL SPECS ---
1. AX Series (General Purpose):
   - Accuracy: ±0.3% FS.
   - Supply: 100-240V AC.
   - Outputs: Relay (3A), SSR, or 4-20mA (Current).
   - Sizes: AX4 (48x48), AX7 (72x72), AX9 (96x96), AX3 (96x48).

2. VX Series (Advanced):
   - High speed sampling (50ms).
   - Inputs: Universal (TC/RTD/Voltage/Current).
   - Features: RS485 Communication (on specific models), Retransmission output.
   - Output Types: Relay, SSR, Current (4-20mA), Voltage Pulse.
"""

SYSTEM_INSTRUCTION = f"""
You are EngiBot, a technical sales engineer for Everbolt Engineering.

RULES:
1. Recommend products from 'PRODUCT_CATALOG' ONLY.
2. If user asks technical questions (e.g. "What is the accuracy?", "Does it have RS485?"), look up the answer in 'TECHNICAL_DATA'.
3. Use exact Part Numbers (e.g., "AX4-1A", "TC544C") when quoting.
4. If user speaks Sinhala/Singlish, reply in that language.

DATA:
{PRODUCT_CATALOG}
{TECHNICAL_DATA}
"""

class UserRequest(BaseModel):
    message: str

@app.post("/api/chat")
async def chat(request: UserRequest):
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        prompt = f"{SYSTEM_INSTRUCTION}\n\nUser: {request.message}"
        response = model.generate_content(prompt)
        return {"reply": response.text}
    except Exception as e:
        return {"reply": "Server Error: Make sure API Key is set in Vercel."}

@app.get("/api/download-quote")
async def download_quote():
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="Everbolt Engineering Quotation", ln=True, align='C')
    pdf.cell(200, 10, txt="Generated by EngiBot", ln=True, align='C')
    pdf.ln(10)
    pdf.cell(200, 10, txt="Note: Prices are subject to change. Valid for 7 days.", ln=True, align='L')
    
    pdf_bytes = pdf.output(dest='S').encode('latin-1')
    return Response(content=pdf_bytes, media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=quote.pdf"})

handler = Mangum(app)
