from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import google.generativeai as genai
import os
from fpdf import FPDF
from fastapi.responses import Response

app = FastAPI()

# 1. Setup Gemini
if "GEMINI_API_KEY" in os.environ:
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])

# 2. YOUR STOCK DATA
PRODUCT_CATALOG = """
--- SELEC CONTROLLERS ---
[ID: TC544C] Selec Dual Display Temp Controller, 48x48mm, Relay/SSR Output, 90-270V. Price: 10,750 LKR
[ID: TC544A] Selec Economic Temp Controller, 48x48mm, Relay Output. Price: 11,850 LKR
[ID: HTC405] Selec Humidity & Temp Controller, 36x72mm. Price: 13,660 LKR
[ID: HTC307] Selec Humidity & Temp Controller, 96x96mm, RS485. Price: 33,070 LKR
[ID: TC303AX] Selec Single Display Controller, 96x96mm. Price: 10,310 LKR
[ID: PID500-U] Selec Universal PID, 48x48mm. Price: ~22,500 LKR
[ID: PID110] Selec PID Controller, 96x48mm. Price: 17,280 LKR
[ID: DTC524] Selec Dual Display PID, 48x48mm. Price: 7,025 LKR
[ID: TC513AX] Selec Single Display Controller, 48x48mm. Price: 10,600 LKR
[ID: TC244AX] Selec Dual Display Controller, 72x72mm. Price: 11,500 LKR

--- HANYOUNG NUX CONTROLLERS ---
[ID: AX4-1A] Hanyoung Digital Temp Controller, 48x48mm, Relay+SSR. Price: 16,230 LKR
[ID: AX4-3A] Hanyoung Controller, 48x48mm, 4-20mA Output. Price: 17,800 LKR
[ID: AX9-4A] Hanyoung Controller, 96x96mm, 4-20mA Output. Price: 21,900 LKR
[ID: VX4-USMA] Hanyoung Advanced Controller, Voltage Pulse, 48x48mm. Price: 19,290 LKR
[ID: VX4-RS485] Hanyoung Controller with RS485. Price: 26,430 LKR
[ID: DX3-K] Hanyoung Analog Dial Controller, 96x96mm. Price: 3,500 LKR
"""

TECHNICAL_DATA = """
--- SELEC SPECS ---
1. TC544C / TC544A: Accuracy 0.25% FS. Supply 90-270V. Relay/SSR Output.
2. HTC405: Humidity Sensor HS-A-100 included.
3. PID500: Universal Inputs, Heat-Cool PID.
--- HANYOUNG SPECS ---
1. AX Series: Accuracy 0.3%. Supply 100-240V.
2. VX Series: High speed 50ms sampling. RS485 optional.
"""

SYSTEM_INSTRUCTION = f"""
You are EngiBot, a technical sales engineer for Everbolt Engineering.
1. Recommend products from 'PRODUCT_CATALOG' ONLY.
2. Use exact Part Numbers (e.g., "AX4-1A").
3. If user speaks Sinhala/Singlish, reply in that language.
DATA: {PRODUCT_CATALOG} {TECHNICAL_DATA}
"""

class UserRequest(BaseModel):
    message: str

@app.post("/api/chat")
async def chat(request: UserRequest):
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        prompt = f"{SYSTEM_INSTRUCTION}\n\nUser: {request.message}"
        response = model.generate_content(prompt)
        return {"reply": response.text}
    except Exception as e:
        return {"reply": "Server Error. Check API Key."}

@app.get("/api/download-quote")
async def download_quote():
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="Everbolt Engineering Quotation", ln=True, align='C')
    pdf.cell(200, 10, txt="Generated by EngiBot", ln=True, align='C')
    pdf_bytes = pdf.output(dest='S').encode('latin-1')
    return Response(content=pdf_bytes, media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=quote.pdf"})

# THIS IS THE NEW PART: Serving the Website directly from Python
app.mount("/", StaticFiles(directory="public", html=True), name="static")
"""